chatwoot/charts

Chart.yaml
LICENSE
templates/_helpers.tpl
templates/migrations-job.yaml
templates/rails-deployment.yaml
templates/sidekiq-deployment.yaml
values.yaml

- Switch to k8s jobs to run database-migrations
- helm lifecycle hook set to run on post-install and post-upgrade
Closes #9
Closes #5

feat: Switch from initContainers to Kubernetes jobs to run db migrations

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/web-service.yaml
charts/chatwoot/values.yaml

Allows annotations in chatwoot service for cloud service provider required fields, for example ```cloud.google.com/neg: '{"ingress": true}'```  in the values.yaml file.
Signed-off-by: thundersparkf <devagastya0@gmail.com>

Allows annotations for services to enable cloud provided load balancers

---

charts/chatwoot/Chart.yaml
charts/chatwoot/values.yaml

- Update app version to point to latest chatwoot release v1.19.0

Increment app version to v1.19.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/migrations-job.yaml

`nslookup` of DB hostname was used as DB init check for migration job. This was causing the migration job container to fail multiple times. NSLOOKUP being successful does not equate to DB is ready to accept connections.
This PR changed that to use the `pg_ready` tool which is a much more reliable metric to assess DB ready status.
Fixes #32

feat: use pg_ready for k8s migration job init-check

---

charts/chatwoot/Chart.yaml
charts/chatwoot/values.yaml

* Update charts to chatwoot `v1.22.0`
* https://github.com/chatwoot/chatwoot/releases/tag/v1.22.0

feat: update chart to v1.22.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

* Update charts to chatwoot `v2.0.0`
* https://github.com/chatwoot/chatwoot/releases/tag/v2.0.0

feat: update charts to chatwoot v2.0.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

* Update charts to chatwoot `v2.0.1`
* https://github.com/chatwoot/chatwoot/releases/tag/v2.0.1
﻿

feat: update charts to chatwoot v2.0.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

* Update charts to chatwoot `v2.0.2`
* https://github.com/chatwoot/chatwoot/releases/tag/v2.0.2
﻿
﻿

feat: update charts to chatwoot v2.0.2

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

* Update charts to chatwoot `v2.1.0`
* https://github.com/chatwoot/chatwoot/releases/tag/v2.1.0
﻿
﻿

feat: update charts to v2.1.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.1.1
- https://github.com/chatwoot/chatwoot/releases/tag/v2.1.1

feat: bump chatwoot verison to v2.1.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.5.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.5.0
﻿
﻿

feat: update charts to chatwoot v2.5.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.6.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.6.0
﻿
﻿

feat: update charts to chatwoot v2.6.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.7.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.7.0
﻿
﻿
﻿

feat: update charts to chatwoot v2.7.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/templates/web-deployment.yaml
charts/chatwoot/templates/web-hpa.yaml
charts/chatwoot/templates/web-service.yaml
charts/chatwoot/templates/worker-deployment.yaml
charts/chatwoot/templates/worker-hpa.yaml
charts/chatwoot/values.ci.yaml
charts/chatwoot/values.yaml

Fixes #72 
- add hpa support for web and worker deployments
- autoscale the pods when average CPU utilisation is above 75%
- set default Redis replica count to `1` from `3`
﻿
﻿
﻿

feat: add autoscaling to web and worker pods

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.9.1
- https://github.com/chatwoot/chatwoot/releases/tag/v2.9.1
﻿
Fixes https://github.com/chatwoot/product/issues/529﻿

feat: upgrade charts to chatwoot v2.9.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/env-secret.yaml
charts/chatwoot/templates/web-deployment.yaml
charts/chatwoot/templates/worker-deployment.yaml

The `values.yaml` file suggests that when using an existing secret for postgres secret, this should be specified as `postgresql.auth.existingSecret`. Indeed, this is how the secret is mounted in the migration job.
However, this is inconsistent with how the secret is mounted in Deployments and in the secret environment resource.
This PR makes the use of existingSecret consistent

fix existingSecret for postgres

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.ci.yaml
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.10.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.10.0
﻿

feat: upgrade charts to chatwoot v2.10.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/web-deployment.yaml
charts/chatwoot/templates/worker-deployment.yaml
charts/chatwoot/values.yaml

Recently the location of the existing secret and key location has changed. However, while the migration job did get this change the worker and web deployments were still referencing the old location of the postgres secret key. This PR fixes that. It also allows for specifying the resources for the web and workers independently, since without the having them auto-scale properly is not possible.

Fix the existing postgres secret keys and allow for setting independent resources

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/migrations-job.yaml
charts/chatwoot/templates/web-deployment.yaml
charts/chatwoot/templates/worker-deployment.yaml

The chart has `securityContext` in the `vaules.yaml` file. However, this is misleading as this value is used nowhere in the chart.
This PR sets up all that's necessary to run chatwoot with a non-root user by:
- rendering  `securityContext` in migrate job and deployments
- setting up a temporary volume for cache. The container runs `mkdir` on a temporary folder, and for non-root to work, the folder has to be owned by running user

render security context

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.11.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.11.0
﻿

feat: upgrade charts to chatwoot v2.11.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.12.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.12.0
﻿
wq

feat: upgrade charts to chatwoot v2.12.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.13.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.13.0

feat: upgrade charts to chatwoot v2.13.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.14.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.14.0

feat: upgrade charts to chatwoot v2.14.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.15.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.15.0

feat: upgrade charts to chatwoot v2.15

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/web-deployment.yaml
charts/chatwoot/templates/worker-deployment.yaml

Allows the user to specify custom pod annotations for the `web` and `worker` deployments. This is useful for things like `linkerd` injection, or whatever else the user might need.
I didn't add this to the migrations `Job` spec, not sure if it makes sense there. Could always use another `values.yaml` key if desired.

Support podAnnotations for web and worker deployments

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.17.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.17.0

feat: upgrade charts to chatwoot v2.17.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.17.1
- https://github.com/chatwoot/chatwoot/releases/tag/v2.17.1

chore: update charts to chatwoot v2.17.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.18.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.18.0

feat: upgrade charts to chatwoot v2.18.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.0.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.0.0

chore: upgrade charts to chatwoot v3.0.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.1.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.1.0

chore: upgrade charts to chatwoot v3.1.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.120
- https://github.com/chatwoot/chatwoot/releases/tag/v3.2.0

feat: upgrade charts to chatwoot v3.2.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.3.1
- https://github.com/chatwoot/chatwoot/releases/tag/v3.3.1

feat: upgrade charts to chatwoot v3.3.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/web-deployment.yaml
charts/chatwoot/templates/worker-deployment.yaml

The imagePullSecrets for the web and worker deployments need to be changed.
I changed imagePullSecrets in the value file, but it wasn't used in the web and worker deployment templates, so I added it there.

fix: use imagepullsecret in web-deployment and worker-deployment

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.4.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.4.0

feat: upgrade charts to chatwoot v3.4.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.5.1
- https://github.com/chatwoot/chatwoot/releases/tag/v3.5.1

feat: upgrade charts to chatwoot v3.5.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.6.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.6.0
Fixes https://linear.app/chatwoot/issue/CW-3096/release-charts-and-ami-for-v36

feat: upgrade charts to chatwoot v3.6.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.7.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.7.0

feat: upgrade charts to chatwoot v3.7.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.8.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.8.0

feat: upgrade charts to chatwoot v3.8.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.9.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.9.0

feat: upgrade charts to chatwoot v3.9.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.10.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.10.0

feat: upgrade charts to chatwoot v3.10.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.11.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.11.0

feat: upgrade charts to chatwoot v3.11.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.12.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.12.0

feat: upgrade charts to chatwoot v3.12

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.14.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.14.0

feat: upgrade charts to chatwoot v3.14.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.14.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.14.1

feat: upgrade charts to chatwoot v3.14.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.15.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.15.0

feat: upgrade charts to chatwoot v3.15.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v3.16.0
- https://github.com/chatwoot/chatwoot/releases/tag/v3.16.0

feat: upgrade charts to chatwoot v3.16.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/migrations-job.yaml

To use an internalized image from a private repository, I noticed the ImagePullSecrets were missing for the InitContainers in the CronJob. This update includes the ImagePullSecrets configuration, enabling easier access to private images in custom deployments.

feature: Add Image Pull Secrets for CronJob InitContainers

---

.github/workflows/lint-test.yaml

- Linting gh action for charts repo was broken due to the old Python version. Update it to `3.13`

chore: fix python version in gh action

---

charts/chatwoot/values.v4-upgrade.yaml
charts/chatwoot/values.yaml

Chatwoot v4 and above requires PostgreSQL with pgvector support. Replace the default Bitnami PostgreSQL image with a custom image that has `pgvector` installed.
This only affects users relying on postgres installed via charts.
ref: https://chwt.app/v4/migration

feat: replace postgres image with pgvector support

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- This upgrade will switch to first v4 stable release
- Update charts to chatwoot v4.1.0
- This includes breaking changes
- Please read the migration guide before upgrading to v4 from 3.x.x
- https://chwt.app/v4/migration
- https://github.com/chatwoot/chatwoot/releases/tag/v4.1.0

feat: upgrade charts to chatwoot v4

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v4.2.0
- Please read the migration guide before upgrading to v4 from 3.x.x
- https://chwt.app/v4/migration
- https://github.com/chatwoot/chatwoot/releases/tag/v4.2.0

feat: upgrade charts to chatwoot v4.2.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v4.6.0
- Please read the migration guide before upgrading to v4 from 3.x.x
- https://chwt.app/v4/migration
- https://github.com/chatwoot/chatwoot/releases/tag/v4.6.0

feat: upgrade charts to chatwoot v4.6.0
