templates/_env_rails.tpl
templates/_helpers.tpl
values.yaml

Add `DATABASE_URL` environment variable to support external databases.

chore: fix external postgres support

---

templates/_helpers.tpl
templates/migrations-job.yaml
templates/web-deployment.yaml
templates/web-service.yaml
templates/worker-deployment.yaml
values.yaml

- chore: clean up and organise chart

chore: clean up and organise chart

---

Chart.yaml

chore: update to v1.18.1

---

Chart.yaml
values.yaml

chore: add extra chart.yaml params

---

README.md
charts/chatwoot/Chart.yaml
charts/chatwoot/README.md

doc:  init documentation

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/templates/_helpers.tpl
charts/chatwoot/templates/env-configmap.yaml
charts/chatwoot/templates/ingress.yaml
charts/chatwoot/templates/migrations-job.yaml
charts/chatwoot/templates/serviceaccount.yaml
charts/chatwoot/templates/web-deployment.yaml
charts/chatwoot/templates/web-service.yaml
charts/chatwoot/templates/worker-deployment.yaml

fix: selector issues when upgrading

---

charts/chatwoot/Chart.yaml
charts/chatwoot/values.yaml

- Update charts to Chatwoot v1.20.0

update charts to chatwoot v1.20.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/templates/ingress.yaml
charts/chatwoot/values.yaml

Add ingressClass support

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.2.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.2.0

feat: update charts to chatwoot v2.2.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.2.1
- https://github.com/chatwoot/chatwoot/releases/tag/v2.2.1
﻿

feat: update charts to chatwoot v2.2.1

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.3.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.3.0
﻿
﻿

feat: update charts to chatwoot v2.3.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.3.2
- https://github.com/chatwoot/chatwoot/releases/tag/v2.3.2
﻿
﻿

feat: update charts to chatwoot v2.3.2

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.4.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.4.0
﻿
﻿

feat: update charts to chatwoot v2.4.0

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.4.1
- https://github.com/chatwoot/chatwoot/releases/tag/v2.4.1
﻿
﻿

feat: update charts to chatwoot v2.4.1

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/chatwoot/Chart.lock
charts/chatwoot/Chart.yaml

fix: failing gh actions for testing and releasing charts

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.8.1
- https://github.com/chatwoot/chatwoot/releases/tag/v2.8.1
﻿
Fixes https://github.com/chatwoot/product/issues/529﻿

feat: update charts to chatwoot v2.8.1

---

charts/chatwoot/README.md

Postgres related values changed with the `1.0.0` release of Charts.

doc: update readme to reflect postgres var change

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/values.yaml

- Update charts to chatwoot v2.9.0
- https://github.com/chatwoot/chatwoot/releases/tag/v2.9.0
﻿
Fixes https://github.com/chatwoot/product/issues/529﻿

feat: update charts to chatwoot v2.9.0

---

charts/chatwoot/README.md

- Add missing description for parameter `existingEnvSecret`

doc: add parameter description

---

charts/chatwoot/Chart.yaml
charts/chatwoot/README.md
charts/chatwoot/templates/web-hpa.yaml
charts/chatwoot/templates/worker-hpa.yaml
charts/chatwoot/values.yaml

#104 migrate autoscaling api version from deprecated
